server:
  port: 8083

spring:
  application:
    name: catalog
  data:
    mongodb:
      host: localhost
      port: 49155
      database: shopstyle
      password: mongopw
      username: docker
      authentication-database: admin
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka