version: '3.1'
services:
  customer:
    image: postgres
    container_name: postgresSqlCustomer
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "49153:49153"
    volumes:
      - compass_data:/var/lib/postgresql
    networks:
      - postgres
    restart: unless-stopped

  checkout:
    image: postgres
    container_name: postgresSqlCheckout
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "49154:49154"
    volumes:
      - compass_data:/var/lib/postgresql
    networks:
      - postgres
    restart: unless-stopped

  catalog:
    image: mongo
    container_name: mongoDB
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - "49155:49155"
    volumes:
      - compass_data:/var/lib/postgresql
    networks:
      - postgres
    restart: unless-stopped
# pgadmin:
#     container_name: pgadmin
#     image: dpage/pgadmin4
#     environment:
#       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#        PGADMIN_CONFIG_SERVER_MODE: 'False'
#      volumes:
#        - pgadmin:/var/lib/pgadmin
#      ports:
#        - "5050:80"
#      networks:
#        - postgres
#      restart: unless-stopped

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./dados:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin


networks:
  postgres:
    driver: bridge

volumes:
  compass_data:



